//! Generate GFF3 output files from the corrected pangenome graph.
//!
//! Reconstructs per-genome GFF3 files using corrected cluster IDs and
//! annotations from the pangenome graph, similar to Panaroo's
//! `panaroo-generate-gffs` functionality.

use std::collections::HashMap;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::error::Result;
use crate::graph::{GenomeId, PangenomeGraph};
#[cfg(test)]
use crate::graph::GeneId;

/// Gene info needed for GFF reconstruction.
///
/// Each entry represents a single gene annotation line in the output GFF3.
struct GffGeneEntry {
    gene_id: String,
    cluster_id: String,
    contig: String,
    start: usize,
    end: usize,
    strand: String,
    annotation: Option<String>,
}

/// Write GFF3 files for each genome from the pangenome graph.
///
/// For each genome present in the graph, reconstructs a GFF3 file with
/// corrected cluster IDs and annotations. Genes are sorted by contig and
/// start position for deterministic output.
pub fn write_gff_files(
    graph: &PangenomeGraph,
    output_dir: &Path,
) -> Result<Vec<PathBuf>> {
    let gff_dir = output_dir.join("gff");
    std::fs::create_dir_all(&gff_dir)?;

    // Collect gene entries grouped by genome from the gene_lookup table
    let mut genome_genes: HashMap<GenomeId, Vec<GffGeneEntry>> = HashMap::new();

    // Build reverse index: GeneId -> ClusterId (avoids O(N*M) scan per gene)
    let gene_to_cluster: HashMap<&str, &str> = graph.nodes.values()
        .flat_map(|node| {
            let cid = node.cluster_id.as_str();
            node.gene_members.values().flat_map(move |ids| {
                ids.iter().map(move |id| (id.as_str(), cid))
            })
        })
        .collect();

    for (gene_id, gene) in &graph.gene_lookup {
        let cluster_id = gene_to_cluster.get(gene_id.as_str())
            .map(|s| s.to_string())
            .unwrap_or_else(|| "unknown".to_string());

        let entry = GffGeneEntry {
            gene_id: gene_id.as_str().to_string(),
            cluster_id,
            contig: gene.contig.clone(),
            start: gene.start,
            end: gene.end,
            strand: gene.strand.to_string(),
            annotation: gene.annotation.clone(),
        };

        genome_genes
            .entry(gene.genome_id.clone())
            .or_default()
            .push(entry);
    }

    let mut written_paths = Vec::new();

    // Write one GFF3 file per genome
    let mut genome_names: Vec<GenomeId> = genome_genes.keys().cloned().collect();
    genome_names.sort();

    for genome_id in &genome_names {
        let entries = genome_genes.get_mut(genome_id).unwrap();

        // Sort by contig name, then by start position
        entries.sort_by(|a, b| {
            a.contig
                .cmp(&b.contig)
                .then_with(|| a.start.cmp(&b.start))
        });

        let filename = format!("{}.gff", sanitize_filename(genome_id.as_str()));
        let path = gff_dir.join(&filename);
        write_single_gff(genome_id.as_str(), entries, &path)?;
        written_paths.push(path);
    }

    Ok(written_paths)
}

/// Find the cluster ID that contains a given gene.
#[cfg(test)]
fn find_cluster_for_gene(graph: &PangenomeGraph, gene_id: &GeneId) -> String {
    for node in graph.nodes.values() {
        for member_ids in node.gene_members.values() {
            if member_ids.iter().any(|m| m == gene_id.as_str()) {
                return node.cluster_id.to_string();
            }
        }
    }
    // Fallback: gene not found in any cluster node's gene_members
    "unknown".to_string()
}

/// Write a single GFF3 file for one genome.
fn write_single_gff(
    genome_id: &str,
    entries: &[GffGeneEntry],
    path: &Path,
) -> Result<()> {
    let mut file = std::fs::File::create(path)?;
    let mut writer = std::io::BufWriter::new(&mut file);

    // GFF3 header
    writeln!(writer, "##gff-version 3")?;
    writeln!(writer, "# Generated by PanMiner for genome: {}", genome_id)?;

    // Collect unique contigs for the FASTA section
    let mut contigs: Vec<&str> = entries
        .iter()
        .map(|e| e.contig.as_str())
        .collect();
    contigs.sort();
    contigs.dedup();

    // Write gene annotation lines
    for entry in entries {
        let attributes = format_attributes(
            &entry.gene_id,
            &entry.cluster_id,
            entry.annotation.as_deref(),
        );

        writeln!(
            writer,
            "{}\tpanminer\tCDS\t{}\t{}\t.\t{}\t0\t{}",
            entry.contig,
            entry.start,
            entry.end,
            entry.strand,
            attributes
        )?;
    }

    // Write FASTA section header (contig sequences are not available from
    // the graph alone, but the section header is written for compatibility)
    writeln!(writer, "##FASTA")?;
    for contig in contigs {
        writeln!(writer, ">{}", contig)?;
        // Contig sequences would require original input data; placeholder
        writeln!(writer, "# sequence not available")?;
    }

    drop(writer);
    Ok(())
}

/// Format GFF3 attributes column for a gene entry.
fn format_attributes(gene_id: &str, cluster_id: &str, annotation: Option<&str>) -> String {
    let mut attrs = format!("ID={};cluster={}", gene_id, cluster_id);

    if let Some(anno) = annotation {
        if !anno.is_empty() {
            attrs.push_str(&format!(";annotation={}", escape_gff_attribute(anno)));
        }
    }

    attrs
}

/// Escape special characters in GFF3 attribute values.
///
/// Per the GFF3 spec, attribute values must escape: tab, newline, carriage
/// return, percent, semicolon, equals, ampersand, comma.
fn escape_gff_attribute(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\t' => out.push_str("%09"),
            '\n' => out.push_str("%0A"),
            '\r' => out.push_str("%0D"),
            '%' => out.push_str("%25"),
            ';' => out.push_str("%3B"),
            '=' => out.push_str("%3D"),
            '&' => out.push_str("%26"),
            ',' => out.push_str("%2C"),
            _ => out.push(ch),
        }
    }
    out
}

/// Sanitize a genome ID for use as a filename.
fn sanitize_filename(s: &str) -> String {
    s.replace(|c: char| c == '/' || c == '\\' || c == ':', "_")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::{Gene, GeneCluster, GenomeMetadata, Node, Strand};

    fn make_test_graph() -> PangenomeGraph {
        let mut graph = PangenomeGraph::new();

        // Create two genes in genome1
        let mut gene_a = Gene::new("geneA", GenomeId::new("genome1"));
        gene_a.contig = "contig1".to_string();
        gene_a.start = 100;
        gene_a.end = 500;
        gene_a.strand = Strand::Plus;
        gene_a.annotation = Some("hypothetical protein".to_string());

        let mut gene_b = Gene::new("geneB", GenomeId::new("genome1"));
        gene_b.contig = "contig1".to_string();
        gene_b.start = 600;
        gene_b.end = 900;
        gene_b.strand = Strand::Minus;
        gene_b.annotation = None;

        let mut gene_c = Gene::new("geneC", GenomeId::new("genome2"));
        gene_c.contig = "chr1".to_string();
        gene_c.start = 50;
        gene_c.end = 300;
        gene_c.strand = Strand::Plus;
        gene_c.annotation = Some("transposase".to_string());

        // Add genes to gene_lookup
        graph.gene_lookup.insert(GeneId::new("geneA"), gene_a);
        graph.gene_lookup.insert(GeneId::new("geneB"), gene_b);
        graph.gene_lookup.insert(GeneId::new("geneC"), gene_c);

        // Create clusters and nodes with gene_members
        let mut cluster1 = GeneCluster::new("cluster_0");
        cluster1.add_gene(GeneId::new("geneA"));
        cluster1.add_gene(GeneId::new("geneB"));
        cluster1.support = 1;

        let mut cluster2 = GeneCluster::new("cluster_1");
        cluster2.add_gene(GeneId::new("geneC"));
        cluster2.support = 1;

        let mut node1 = Node::from_cluster(&cluster1);
        node1.gene_members.insert(
            GenomeId::new("genome1"),
            vec!["geneA".to_string(), "geneB".to_string()],
        );
        node1.genomes.insert(GenomeId::new("genome1"));

        let mut node2 = Node::from_cluster(&cluster2);
        node2.gene_members.insert(
            GenomeId::new("genome2"),
            vec!["geneC".to_string()],
        );
        node2.genomes.insert(GenomeId::new("genome2"));

        graph.add_node(node1);
        graph.add_node(node2);

        // Add genome metadata
        graph.genomes.insert(
            GenomeId::new("genome1"),
            GenomeMetadata {
                id: GenomeId::new("genome1"),
                source_file: "genome1.gff".to_string(),
                num_contigs: 1,
                total_genes: 2,
            },
        );
        graph.genomes.insert(
            GenomeId::new("genome2"),
            GenomeMetadata {
                id: GenomeId::new("genome2"),
                source_file: "genome2.gff".to_string(),
                num_contigs: 1,
                total_genes: 1,
            },
        );

        graph
    }

    #[test]
    fn test_gff_output_format() {
        let graph = make_test_graph();
        let tmp_dir = tempfile::tempdir().unwrap();
        let paths = write_gff_files(&graph, tmp_dir.path()).unwrap();

        assert_eq!(paths.len(), 2);

        // Read genome1 GFF and verify contents
        let gff1_path = tmp_dir.path().join("gff").join("genome1.gff");
        assert!(gff1_path.exists());
        let content = std::fs::read_to_string(&gff1_path).unwrap();

        assert!(content.starts_with("##gff-version 3"));
        assert!(content.contains("contig1\tpanminer\tCDS\t100\t500\t.\t+\t0\tID=geneA;cluster=cluster_0;annotation=hypothetical protein"));
        assert!(content.contains("contig1\tpanminer\tCDS\t600\t900\t.\t-\t0\tID=geneB;cluster=cluster_0"));
        assert!(content.contains("##FASTA"));
    }

    #[test]
    fn test_gff_output_genome2() {
        let graph = make_test_graph();
        let tmp_dir = tempfile::tempdir().unwrap();
        write_gff_files(&graph, tmp_dir.path()).unwrap();

        let gff2_path = tmp_dir.path().join("gff").join("genome2.gff");
        assert!(gff2_path.exists());
        let content = std::fs::read_to_string(&gff2_path).unwrap();

        assert!(content.contains("chr1\tpanminer\tCDS\t50\t300\t.\t+\t0\tID=geneC;cluster=cluster_1;annotation=transposase"));
    }

    #[test]
    fn test_gff_sort_order() {
        let graph = make_test_graph();
        let tmp_dir = tempfile::tempdir().unwrap();
        write_gff_files(&graph, tmp_dir.path()).unwrap();

        let gff1_path = tmp_dir.path().join("gff").join("genome1.gff");
        let content = std::fs::read_to_string(&gff1_path).unwrap();

        // geneA (start=100) should appear before geneB (start=600)
        let pos_a = content.find("geneA").unwrap();
        let pos_b = content.find("geneB").unwrap();
        assert!(pos_a < pos_b, "genes should be sorted by start position");
    }

    #[test]
    fn test_escape_gff_attribute() {
        assert_eq!(escape_gff_attribute("simple"), "simple");
        assert_eq!(escape_gff_attribute("with;semi"), "with%3Bsemi");
        assert_eq!(escape_gff_attribute("with=eq"), "with%3Deq");
        assert_eq!(escape_gff_attribute("with%percent"), "with%25percent");
        assert_eq!(escape_gff_attribute("with,comma"), "with%2Ccomma");
        assert_eq!(escape_gff_attribute("with&amp"), "with%26amp");
    }

    #[test]
    fn test_format_attributes_with_annotation() {
        let attrs = format_attributes("gene1", "cluster_0", Some("hypothetical protein"));
        assert_eq!(attrs, "ID=gene1;cluster=cluster_0;annotation=hypothetical protein");
    }

    #[test]
    fn test_format_attributes_without_annotation() {
        let attrs = format_attributes("gene1", "cluster_0", None);
        assert_eq!(attrs, "ID=gene1;cluster=cluster_0");
    }

    #[test]
    fn test_format_attributes_empty_annotation() {
        let attrs = format_attributes("gene1", "cluster_0", Some(""));
        assert_eq!(attrs, "ID=gene1;cluster=cluster_0");
    }

    #[test]
    fn test_sanitize_filename() {
        assert_eq!(sanitize_filename("genome1"), "genome1");
        assert_eq!(sanitize_filename("path/to/genome"), "path_to_genome");
        assert_eq!(sanitize_filename("win\\path"), "win_path");
        assert_eq!(sanitize_filename("name:with:colons"), "name_with_colons");
    }

    #[test]
    fn test_find_cluster_for_gene() {
        let graph = make_test_graph();
        assert_eq!(
            find_cluster_for_gene(&graph, &GeneId::new("geneA")),
            "cluster_0"
        );
        assert_eq!(
            find_cluster_for_gene(&graph, &GeneId::new("geneC")),
            "cluster_1"
        );
        assert_eq!(
            find_cluster_for_gene(&graph, &GeneId::new("unknown_gene")),
            "unknown"
        );
    }

    #[test]
    fn test_empty_graph() {
        let graph = PangenomeGraph::new();
        let tmp_dir = tempfile::tempdir().unwrap();
        let paths = write_gff_files(&graph, tmp_dir.path()).unwrap();
        assert!(paths.is_empty());
    }
}